/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MutualFundsRouteImport } from './routes/mutual-funds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CibilRouteImport } from './routes/cibil'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MutualFundsRoute = MutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CibilRoute = CibilRouteImport.update({
  id: '/cibil',
  path: '/cibil',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/banking': typeof BankingRoute
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/banking': typeof BankingRoute
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/banking': typeof BankingRoute
  '/cibil': typeof CibilRoute
  '/contact': typeof ContactRoute
  '/insurance': typeof InsuranceRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/mutual-funds': typeof MutualFundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/cibil'
    | '/contact'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/cibil'
    | '/contact'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/banking'
    | '/cibil'
    | '/contact'
    | '/insurance'
    | '/loans'
    | '/login'
    | '/mutual-funds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BankingRoute: typeof BankingRoute
  CibilRoute: typeof CibilRoute
  ContactRoute: typeof ContactRoute
  InsuranceRoute: typeof InsuranceRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  MutualFundsRoute: typeof MutualFundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mutual-funds': {
      id: '/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/mutual-funds'
      preLoaderRoute: typeof MutualFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cibil': {
      id: '/cibil'
      path: '/cibil'
      fullPath: '/cibil'
      preLoaderRoute: typeof CibilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BankingRoute: BankingRoute,
  CibilRoute: CibilRoute,
  ContactRoute: ContactRoute,
  InsuranceRoute: InsuranceRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  MutualFundsRoute: MutualFundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
